### ISSUE TITLE
chokes on foundation abide css

### ISSUE THREAD

**Issue by airtonix** [macbre/analyze-css#107]
I know foundation isn't terribly great in a number of areas, but surely the following is valid css: 

```
[data-abide] .error small.error
```

getting the following error : 
```
/home/zenobius/Projects/USA/usa002/node_modules/fe-gulp/node_modules/analyze-css/node_modules/slick/parser.js:227
        if (replaced === expression) throw new Error(original + ' is an invali
                                           ^
Error: "[data-abide]" .error small.error is an invalid expression
  at new Expressions (/home/zenobius/Projects/USA/usa002/node_modules/fe-gulp/node_modules/analyze-css/node_modules/slick/parser.js:227:44)
  at parse (/home/zenobius/Projects/USA/usa002/node_modules/fe-gulp/node_modules/analyze-css/node_modules/slick/parser.js:247:54)

```

node: v0.12.7
npm: v2.11.3
analyze-css: v0.9.6

**Comment by airtonix** [comment]
nvm problem with either `foundation`  or `lib-sass`

https://github.com/zurb/foundation/issues/6957

**Comment by macbre** [comment]
@airtonix, thanks for filing an issue.

CSS parsing error should be gracefully handled. I assume that analyze-css simply threw an error and died.

**Comment by macbre** [comment]
@airtonix, are you that analyze-css fails?

```
$ echo '[data-abide] .error small.error' | DEBUG=* ./bin/analyze-css.js -

...
  analyze-css error: {"reason":"missing '{'","line":2,"column":1,"source":""} +0ms
...
```

```json
{"offenders":{"parsingErrors":["missing '{' @ 2:1"]}}
```
